version: '2'
services:
  mallcloud-authentication-server:
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    volumes:
      - /data/logs/mallcloud-authentication-server/:/logs/mallcloud-authentication-server/
    networks:
      - mallcloud

  mallcloud-rbac:
    build:
      context: ./
      dockerfile: Dockerfile-rbac
    restart: always
    volumes:
      - /data/logs/mallcloud-rbac-service/:/logs/mallcloud-rbac-service/
    networks:
      - mallcloud

  mallcloud-admin:
    build:
      context: ./
      dockerfile: Dockerfile-admin
    restart: always
    ports:
      - 10001:10001
    volumes:
      - /data/logs/mallcloud-admin/:/logs/mallcloud-admin/
    networks:
      - mallcloud

  mallcloud-monitor:
    build:
      context: ./
      dockerfile: Dockerfile-monitor
    restart: always
    ports:
      - 10002:10002
    volumes:
      - /data/logs/mallcloud-monitor/:/logs/mallcloud-monitor/
    networks:
      - mallcloud

  mallcloud-gateway:
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    ports:
      - 10000:10000
    depends_on:
      - mallcloud-authentication-server
    volumes:
      - /data/logs/mallcloud-gateway/:/logs/mallcloud-gateway/
    networks:
      - mallcloud

networks:
  mallcloud:
