version: '2'
services:
  mallcloud-registry:
    build:
      context: ./
      dockerfile: Dockerfile-registry
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /data/logs/mallcloud-registry/:/logs/mallcloud-registry/
    networks:
      - mallcloud

  mallcloud-config:
    links:
      - mallcloud-registry
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always
    environment:
      - EUREKA_SERVER_HOST=mallcloud-registry
    depends_on:
      - mallcloud-registry
    volumes:
      - /data/logs/mallcloud-config/:/logs/mallcloud-config/
    networks:
      - mallcloud

networks:
  mallcloud:
